[Ebyte_EoRa-HUB]
extends = esp32_base
board = ebyte_eora-hub
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
build_flags =
  ${esp32_base.build_flags}
  -I variants/ebyte_eora_hub
  -D EBYTE_EORA_HUB
 ; -D P_LORA_DIO_1=14
  -D P_LORA_DIO_9=14
  -D P_LORA_DIO_1=P_LORA_DIO_9
  -D P_LORA_BUSY=13
  -D P_LORA_NSS=8
  -D P_LORA_RESET=12
  -D P_LORA_SCLK=9
  -D P_LORA_MISO=11
  -D P_LORA_MOSI=10
  -D P_LORA_TX_LED=35
  -D PIN_VBAT_READ=1
  -D PIN_USER_BTN=0
  -D PIN_BOARD_SDA=18
  -D PIN_BOARD_SCL=17
  -D PIN_OLED_RESET=21
  -D RADIO_CLASS=CustomLR1121
  -D WRAPPER_CLASS=CustomLR1121Wrapper
  -D LORA_TX_POWER=22
  -D LR11X0_DIO3_TCXO_VOLTAGE=1.8
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/ebyte_eora_hub>
lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit SSD1306 @ ^2.5.13

; === EByte EORA_HUB with LR1121 environments ===
[env:Ebyte_EoRa-HUB_Repeater]
extends = Ebyte_EoRa-HUB
build_flags =
  ${Ebyte_EoRa-HUB.build_flags}
  -D DISPLAY_CLASS=SSD1306Display
  -D ADVERT_NAME='"EORA_HUB-1121 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DEVICE_TYPE_REPEATER
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_repeater>
lib_deps =
  ${Ebyte_EoRa-HUB.lib_deps}
  ${esp32_ota.lib_deps}

[env:Ebyte_EoRa-HUB_terminal_chat]
extends = Ebyte_EoRa-HUB
build_flags =
  ${Ebyte_EoRa-HUB.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps =
  ${Ebyte_EoRa-HUB.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Ebyte_EoRa-HUB_room_server]
extends = Ebyte_EoRa-HUB
build_flags =
  ${Ebyte_EoRa-HUB.build_flags}
  -D DISPLAY_CLASS=SSD1306Display
  -D ADVERT_NAME='"EORA_S3-1121 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_room_server>
lib_deps =
  ${Ebyte_EoRa-HUB.lib_deps}
  ${esp32_ota.lib_deps}

[env:Ebyte_EoRa-HUB_companion_radio_usb]
extends = Ebyte_EoRa-HUB
build_flags =
  ${Ebyte_EoRa-HUB.build_flags}
  -I examples/companion_radio/ui-new
  -D DISPLAY_CLASS=SSD1306Display
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Ebyte_EoRa-HUB.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Ebyte_EoRa-HUB_companion_radio_ble]
extends = Ebyte_EoRa-HUB
build_flags =
  ${Ebyte_EoRa-HUB.build_flags}
  -I examples/companion_radio/ui-new
  -D DISPLAY_CLASS=SSD1306Display
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Ebyte_EoRa-HUB.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Ebyte_EoRa-HUB_companion_radio_wifi]
extends = Ebyte_EoRa-HUB
build_flags =
  ${Ebyte_EoRa-HUB.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SSD1306Display
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"myssid"'
  -D WIFI_PWD='"mypwd"'
  -D OFFLINE_QUEUE_SIZE=256
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
 ${Ebyte_EoRa-HUB.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Ebyte_EoRa-HUB_kiss_modem]
extends = Ebyte_EoRa-HUB
build_src_filter = ${Ebyte_EoRa-HUB.build_src_filter}
  +<../examples/kiss_modem/>
