[Ebyte_EoRa_hub]
extends = esp32_base
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv

build_flags =
  ${esp32_base.build_flags}
  -I variants/ebyte_eora_hub
  -D BOARD_HAS_PSRAM=1
  -D RADIO_CLASS=CustomLR1121
  -D WRAPPER_CLASS=CustomLR1121Wrapper
  -D P_LORA_NSS=8
  -D P_LORA_SCLK=9
  -D P_LORA_MOSI=10
  -D P_LORA_MISO=11
  -D P_LORA_RESET=12
  -D P_LORA_BUSY=13
  -D P_LORA_DIO_9=14
  -D P_LORA_DIO_1=-1
  -D LR11X0_DIO3_TCXO_VOLTAGE=1.8
  -D LORA_TX_POWER=22
  -D DISPLAY_CLASS=SSD1306Display
  -D PIN_OLED_RESET=21
  -D PIN_BOARD_SDA=18
  -D PIN_BOARD_SCL=17
  -D PIN_VBAT_READ=1
  -D ADC_CTRL=37
  -D PIN_SERIAL_TX=43
  -D PIN_SERIAL_RX=44
  -D PIN_USER_BTN=0
  -D LED_POWER=35
  -D RX_BOOSTED_GAIN=1

build_src_filter =
  ${esp32_base.build_src_filter}
  +<../variants/ebyte_eora_hub>

lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit SSD1306 @ ^2.5.13


; === Repeater role ===
[env:Ebyte_EoRa_hub_repeater]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -D ADVERT_NAME='"EORA_HUB-1121 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_repeater>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  ${esp32_ota.lib_deps}


; === ESP-NOW Bridge role ===
[env:Ebyte_EoRa_hub_repeater_bridge_espnow]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -D DISPLAY_CLASS=SSD1306Display
  -D ADVERT_NAME='"ESPNow Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D WITH_ESPNOW_BRIDGE=1
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/bridges/ESPNowBridge.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_repeater>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  ${esp32_ota.lib_deps}


; === Terminal chat role ===
[env:Ebyte_EoRa_hub_terminal_chat]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -D MAX_CONTACTS=300
  -D MAX_GROUP_CHANNELS=1
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_secure_chat/main.cpp>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  densaugeo/base64 @ ~1.4.0


; === Room server role ===
[env:Ebyte_EoRa_hub_room_server]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -D ADVERT_NAME='"EORA_HUB-1121 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_room_server>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  ${esp32_ota.lib_deps}


; === Companion radio (USB) ===
[env:Ebyte_EoRa_hub_companion_radio_usb]
extends = Ebyte_EoRa_hub
upload_speed = 115200
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=300
  -D MAX_GROUP_CHANNELS=8
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  densaugeo/base64 @ ~1.4.0


; === Companion radio (BLE) ===
[env:Ebyte_EoRa_hub_companion_radio_ble]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=300
  -D MAX_GROUP_CHANNELS=8
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  densaugeo/base64 @ ~1.4.0


; === Companion radio (WiFi) ===
[env:Ebyte_EoRa_hub_companion_radio_wifi]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=300
  -D MAX_GROUP_CHANNELS=8
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SSD1306Display
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"myssid"'
  -D WIFI_PWD='"mypwd"'
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  densaugeo/base64 @ ~1.4.0


; === Sensor role ===
[env:Ebyte_EoRa_hub_sensor]
extends = Ebyte_EoRa_hub
build_flags =
  ${Ebyte_EoRa_hub.build_flags}
  -D ADVERT_NAME='"EoRaHub Sensor"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ENV_PIN_SDA=3
  -D ENV_PIN_SCL=4
  -D DISPLAY_CLASS=SSD1306Display
build_src_filter =
  ${Ebyte_EoRa_hub.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<../examples/simple_sensor>
lib_deps =
  ${Ebyte_EoRa_hub.lib_deps}
  ${esp32_ota.lib_deps}